package selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Testes {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\Ygor\\Desktop\\APIWEBDRIVER\\chromedriver_win32\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }

  public void iniciais(){
    driver.get("http://live.demoguru99.com/index.php/");
    driver.manage().window().setSize(new Dimension(1050, 708));
  }


  @Test
  public void test1() throws Exception {
    iniciais();
    int nteste = 1;
    //Página inicial
    String title1 = driver.findElement(By.xpath("//*[@id=\"top\"]/body/div/div/div[2]/div/div[1]/div/div/h2")).getText();//Obter título 1
    driver.findElement(By.cssSelector(".nav-1 > .level0")).click();//Click Mobile
    String title2 = driver.findElement(By.xpath("//*[@id=\"top\"]/body/div/div/div[2]/div/div[2]/div[1]/div[1]/h1")).getText();//Obter título 2
    driver.findElement(By.cssSelector(".category-products > .toolbar > .sorter select")).click();
    //Listar celulares
    String celular1, celular2, celular3;
    celular1 = driver.findElement(By.xpath("//*[@id=\"top\"]/body/div/div/div[2]/div/div[2]/div[1]/div[3]/ul/li[1]/div/h2/a")).getText();//Obter cel1
    celular2 = driver.findElement(By.xpath("//*[@id=\"top\"]/body/div/div/div[2]/div/div[2]/div[1]/div[3]/ul/li[2]/div/h2/a")).getText();//Obter cel2
    celular3 = driver.findElement(By.xpath("//*[@id=\"top\"]/body/div/div/div[2]/div/div[2]/div[1]/div[3]/ul/li[3]/div/h2/a")).getText();//Obter cel3
    {
      //Classificação por nome
      WebElement dropdown = driver.findElement(By.cssSelector(".category-products > .toolbar > .sorter select"));//Clickdropdown
      dropdown.findElement(By.xpath("//*[@id=\"top\"]/body/div/div/div[2]/div/div[2]/div[1]/div[3]/div[1]/div[1]/div/select/option[2]")).click();//Dropdown
      driver.findElement(By.cssSelector(".category-products > .toolbar > .sorter select")).click();
    }
    try {
      assertEquals("THIS IS DEMO SITE FOR   ", title1);//Comparação título 1
      assertEquals("MOBILE", title2);//Comparação título 2
      System.out.println("Test case[" + nteste + "]: Passou");
    } catch (Exception Ex) {
      System.out.println("Test case[" + nteste + "]: Falhou");
    }
    System.out.println("TITULO 1: " + title1);
    System.out.println("TITULO 2: " + title2);
    System.out.println("Lista de celulares: \n" + celular1 + "\n" + celular2 + "\n" + celular3 + "\n");
    Thread.sleep(2500);
    driver.quit();
  }

  @Test
  public void test2() throws Exception{
    iniciais();
    int nteste = 2;
    Thread.sleep(1000);
    driver.findElement(By.linkText("MOBILE")).click();
    String actualPrice = driver.findElement(By.id("product-price-1")).getText();
    driver.findElement(By.cssSelector(".item:nth-child(1) .product-name > a")).click();
    String actualPriceDetails = driver.findElement(By.id("product-price-1")).getText();
    try{
      assertEquals(actualPrice, actualPriceDetails);
      System.out.println("Test case[" + nteste + "]: Passed");
    }catch(Exception ex){
      System.out.println("Test case[" + nteste + "]: Failed" + ex);
    }
    System.out.println("Primeiro preço:\n" + actualPrice + "Segundo preço:\n" + actualPriceDetails);
    Thread.sleep(3000);
    driver.quit();
  }

  @Test
  public void test3() throws Exception{
    iniciais();
    int nteste = 3;
    driver.findElement(By.cssSelector(".nav-1 > .level0")).click();
    driver.findElement(By.cssSelector(".item:nth-child(3) .actions span > span")).click();
    driver.findElement(By.xpath(".//*[@id='shopping-cart-table']/tbody/tr/td[4]/input")).click();
    driver.findElement(By.xpath(".//*[@id='shopping-cart-table']/tbody/tr/td[4]/input")).sendKeys("1000");
    driver.findElement(By.cssSelector(".button:nth-child(2) > span > span")).click();
    String spanactual = driver.findElement(By.xpath("//*[@id=\"top\"]/body/div/div/div[2]/div/div/div/ul/li/ul/li/span")).getText();//Obter mensagem de erro
    String spanexpected = "The requested quantity for “SONY XPERiA” is not available";
    try{
      if(spanexpected.contains(spanactual)) {
        System.out.println("Test case[" + nteste + "]: Passed");
      } else {
        System.out.println("Test case[" + nteste + "]: Falhou");
        assertEquals(spanexpected,spanactual);
      }
    }catch(Exception Ex){
      System.out.println("Test case[" + nteste + "]: Falhou");
    }
    //assertEquals(spanexpected, spanactual);
    Thread.sleep(1000);
    driver.quit();
  }

  @Test
  public void test4() throws Exception {
    iniciais();
    int nteste = 4;
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".nav-1 > .level0")).click();//CLICK MOBILE
    driver.findElement(By.xpath("//*[@id=\"top\"]/body/div/div/div[2]/div/div[2]/div[1]/div[3]/ul/li[1]/div/div[3]/ul/li[2]/a")).click();//clickexperia
    driver.findElement(By.xpath("//*[@id=\"top\"]/body/div/div/div[2]/div/div[2]/div[1]/div[3]/ul/li[2]/div/div[3]/ul/li[2]/a")).click();//clickiphone
    String prod1 = driver.findElement(By.xpath("//*[@id=\"top\"]/body/div/div/div[2]/div/div[2]/div[1]/div[3]/ul/li[1]/div/h2/a")).getText();//XPERIA
    String prod2 = driver.findElement(By.xpath("//*[@id=\"top\"]/body/div/div/div[2]/div/div[2]/div[1]/div[3]/ul/li[2]/div/h2/a")).getText();//IPHONE
    driver.findElement(By.cssSelector(".block-content:nth-child(2) span > span")).click();//botãocompare
    vars.put("win9431", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win9431").toString());
    String prod1comp = driver.findElement(By.xpath("//*[@id=\"product_comparison\"]/tbody[1]/tr[1]/td[1]/h2/a")).getText();
    String prod2comp = driver.findElement(By.xpath("//*[@id=\"product_comparison\"]/tbody[1]/tr[1]/td[2]/h2/a")).getText();
    driver.findElement(By.cssSelector(".buttons-set span > span")).click();
    driver.switchTo().window(vars.get("root").toString());
    try{
      assertEquals(prod1, prod1comp);
      assertEquals(prod2, prod2comp);
      System.out.println("Test case[" + nteste + "]: Passou");
    }catch(Exception Ex){
      System.out.println("Test case[" + nteste + "]: Falhou");
    }
    driver.close();
    driver.quit();
  }

  @Test
  public void test5() throws Exception{
    /*É NECESSÁRIO ALTERAR OS CAMPOS PARA REALIZAR O REGISTRO*/
    iniciais();
    int nteste = 5;
    driver.findElement(By.cssSelector(".skip-account > .label")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.cssSelector(".col-1 span > span")).click();
    driver.findElement(By.id("firstname")).sendKeys("NOMEALEATORIO3");//NECESSÁRIO ALTERAR
    driver.findElement(By.id("middlename")).sendKeys("ALEATORIO2");
    driver.findElement(By.id("lastname")).sendKeys("GREEN2");//NECESSÁRIO ALTERAR
    driver.findElement(By.id("email_address")).click();
    driver.findElement(By.id("email_address")).sendKeys("CLEBER124@GMAIL.COM");//NECESSÁRIO ALTERAR
    driver.findElement(By.id("password")).sendKeys("123456");
    driver.findElement(By.id("confirmation")).sendKeys("123456");
    driver.findElement(By.cssSelector(".button:nth-child(2) > span > span")).click();
    Thread.sleep(2000);
    String msgregistro = driver.findElement(By.xpath("//*[@id=\"top\"]/body/div/div/div[2]/div/div[2]/div/div/ul/li/ul/li/span")).getText();
    driver.findElement(By.linkText("TV")).click();
    driver.findElement(By.linkText("Add to Wishlist")).click();
    driver.findElement(By.cssSelector(".btn-share > span > span")).click();
    driver.findElement(By.id("email_address")).sendKeys("tkqueiroz244@gmail.com");
    driver.findElement(By.id("message")).click();
    driver.findElement(By.id("message")).sendKeys("olá");
    driver.findElement(By.cssSelector(".buttons-set span > span")).click();
    String msgwishlist = driver.findElement(By.xpath("//*[@id=\"top\"]/body/div/div/div[2]/div/div[2]/div/div[1]/ul/li/ul/li/span")).getText();
    System.out.println("Test case[" + nteste + "]: Passou");
    System.out.println("MENSAGEM DE REGISTRO: " + msgregistro);
    System.out.println("MENSAGEM WISHLIST: " + msgwishlist);
  }

  @Test
  public void test6() throws Exception {
    /*--É NECESSÁRIO FECHAR O ANUNCIO QUE SERÁ EXIBIDO NAS ÚLTIMAS ETAPAS DO TESTE
     O ANUNCIO IMPOSSIBILITA A INTERAÇÃO COM O BOTÃO.--*/
    iniciais();
    int nteste = 6;
    driver.findElement(By.cssSelector(".skip-account > .label")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.id("email")).sendKeys("ygorverde572@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("123456");
    driver.findElement(By.id("send2")).click();
    String orderNumber = driver.findElement(By.xpath("//*[@id=\"my-orders-table\"]/tbody/tr[1]/td[1]")).getText();
    driver.findElement(By.xpath("//*[@id=\"my-orders-table\"]/tbody/tr[1]/td[6]/span/a[2]")).click();
    {
      WebElement element = driver.findElement(By.xpath("//*[@id=\"shopping-cart-table\"]/tbody/tr/td[4]/input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".button:nth-child(2) > span > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.xpath("//*[@id=\"shopping-cart-table\"]/tbody/tr/td[4]/input")).clear();
    driver.findElement(By.xpath("//*[@id=\"shopping-cart-table\"]/tbody/tr/td[4]/input")).sendKeys("10");
    driver.findElement(By.xpath("//*[@id=\"shopping-cart-table\"]/tbody/tr/td[4]/button")).click();
    String ordervalue = driver.findElement(By.xpath("//*[@id=\"shopping-cart-totals-table\"]/tfoot/tr/td[2]/strong/span")).getText();
    assertEquals("$5,000.00", ordervalue);
    driver.findElement(By.xpath("//*[@id=\"region_id\"]")).click();
    {
      WebElement dropdown = driver.findElement(By.id("region_id"));
      dropdown.findElement(By.xpath("//option[. = 'California']")).click();
    }
    driver.findElement(By.xpath("//*[@id=\"region_id\"]")).click();//ID REGIÃO
    driver.findElement(By.xpath("//*[@id=\"postcode\"]")).click();//ID POSTCODE
    driver.findElement(By.xpath("//*[@id=\"postcode\"]")).sendKeys("411001242");
    driver.findElement(By.cssSelector(".method-checkout-cart-methods-onepage-bottom span > span")).click();
    driver.findElement(By.xpath("//*[@id=\"billing-buttons-container\"]/button")).click();
    WebDriverWait wait = new WebDriverWait(driver, 130);
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[@id='shipping-method-buttons-container']/button/span/span")));
    driver.findElement(By.xpath("//div[@id='shipping-method-buttons-container']/button/span/span")).click();
    driver.findElement(By.cssSelector("#shipping-method-buttons-container > .button")).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id=\"dt_method_checkmo\"]/label")));
    driver.findElement(By.xpath("//*[@id=\"dt_method_checkmo\"]/label")).click();
    Thread.sleep(5000);//Temporizador para fechar o anúncio
    driver.findElement(By.cssSelector("#payment-buttons-container > .button")).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id=\"review-buttons-container\"]/button")));
    driver.findElement(By.xpath("//*[@id=\"review-buttons-container\"]/button")).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id=\"top\"]/body/div/div/div[2]/div/div/p[1]/a")));
    String order = driver.findElement(By.xpath("//*[@id=\"top\"]/body/div/div/div[2]/div/div/p[1]/a")).getText();
    System.out.println("Test case[" + nteste + "]: Passou");
    System.out.println("Pedido anterior: " + orderNumber + "\nPedido novo: " + order);
    Thread.sleep(3000);
    driver.quit();
  }

 }

